volumes:
  lexia_postgres_data:

services:
  lexiadb:
    image: postgres:17-alpine
    container_name: lexia_postgres
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - lexia_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  lexia:
    build: .
    container_name: lexia_app
    depends_on:
      lexiadb:
        condition: service_healthy
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXP_SECONDS: ${ACCESS_TOKEN_EXP_SECONDS}
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
