volumes:
  snapkeep_postgres_data:
  snapkeep_redis_data:

services:
  snapkeepdb:
    image: postgres:17-alpine
    container_name: snapkeep_postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - snapkeep_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  snapkeep:
    build: .
    container_name: snapkeep_app
    depends_on:
      snapkeepdb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      BACKUP_FOLDER_PATH: /app/backups
    ports:
      - "8001:8001"
    volumes:
      - ${BACKUP_FOLDER_PATH}:/app/backups
    restart: unless-stopped
