name: CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Build and start containers (no cache, always pull latest)
        run: docker compose up -d --pull always --build --remove-orphans
      - name: Remove dangling images
        run: docker image prune --all --force
      - name: Remove unused volumes
        run: docker volume prune --force

    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      PORT: ${{ vars.PORT }}
      DB_CONNECTION_URL: ${{ vars.DB_CONNECTION_URL }}
      DB_CONNECTION_STRING: ${{ vars.DB_CONNECTION_STRING }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      ACCESS_TOKEN_SECRET: ${{ vars.ACCESS_TOKEN_SECRET }}
      ACCESS_TOKEN_EXP_SECONDS: ${{ vars.ACCESS_TOKEN_EXP_SECONDS }}
      GOOGLE_CLOUD_PROJECT_ID: ${{ vars.GOOGLE_CLOUD_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY_OUTSIDE_PATH: ${{ vars.GOOGLE_SERVICE_ACCOUNT_KEY_OUTSIDE_PATH }}
